### PR TITLE
Update NW.js to 0.84.0, released 2024-02-05

### LINKED ISSUE #292: Version of nw.js is old
The version of nw.js currently used to build TiddlyDesktop is 0.77.0, which was [released on June 5, 2023](https://nwjs.io/blog/v0.77.0/). Version 0.84.0 of nw.js was [released a month ago](https://nwjs.io/blog/v0.84.0/), so it's probably worth upgrading to keep current with browser bugfixes.

### PR DESCRIPTION
**Pull request by rmunn**
NW.js 0.84.0 comes with Chromium 121.0.6167.139 and Node 21.1.0.

Fixes #292.

### CODE REVIEW

**Comment by rmunn** [comment]
With the new CI infrastructure it's literally as easy as changing a single file to update the nw.js version included in TiddlyDesktop. Previously you would have had to edit multiple lines in both download-nwjs.sh and bld.sh, but now they all get their data from a single source of truth.

**Comment by Jermolene** [comment]
Thanks @rmunn – I'm going to try to make another release, this time I'm using a mobile device on a train, so will be good practice.

**Comment by Jermolene** [comment]
Hi @rmunn I used a slightly different procedure because of being on mobile:

1. Edit package.json via GH web interface
2. Create a draft release, assigning the vX.X.X tag at the same time

I think you won't be able to see the draft release, but it is not showing any files. I do see the build products if I inspect the action.

**Comment by rmunn** [comment]
I only set it up to create a draft release when a tag is pushed, not when it's created. If you create the tag via the GItHub web UI then it doesn't count as a push. When you get home, you should be able to `git push origin :v0.0.21` (note the colon) to delete the tag, then `git tag v0.0.21` and `git push v0.0.21` to push it again, and that should trigger the draft release getting created and the files uploaded.

**Pull request merged**
